# -*- coding: utf-8 -*-
"""Management_projet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PwKuDDGpC0bllu6D9npHC5grwwFzw57Z

# MANAGEMENT DE PROJET DATA

## ANALYSE EXPLORATOIRE BOXTIME RETARDS

Objectif de l’analyse

L’objectif de cette analyse exploratoire est d’identifier les facteurs susceptibles d’expliquer les retards de livraison afin de construire, dans un second temps, un tableau de bord décisionnel permettant de piloter la performance logistique.

# I- Exploration et prise d'informations stratégiques du jeu de données

##1- Importation
"""

# Importer des librairies

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Importer et charger les données (les jeux de données)
from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/Management de projet data/boxintime_retards_livraisons_2019_2024_v2.csv"
df = pd.read_csv(path)

# Afficher le df
df.head()

"""## 2- Informations sur le df"""

# les informations du df
df.info()

"""Résumé des informations du jeu de données

Le jeu de données contient 1 825 observations, correspondant à 1 825 livraisons, et 14 variables.
Aucune valeur manquante n’est présente, ce qui indique une bonne qualité globale des données.

Les variables se répartissent en :

7 variables numériques, incluant notamment le retard de livraison (en jours), qui constitue la variable cible, ainsi que des informations logistiques (poids, prix, dimensions).

7 variables catégorielles, décrivant le contexte de la livraison (région, canal, type de produit, transporteur) et des variables temporelles actuellement stockées au format texte (dates de commande et de livraison, délai prévu).

Certaines variables temporelles nécessitent une conversion de type avant analyse, mais le jeu de données est globalement propre, exploitable et adapté à une analyse exploratoire et à des analyses prédictives sur les retards de livraison.

*la variable « Retard (en j) » est considérée comme la variable cible, car elle permet de mesurer la performance de livraison.*
"""

# Taille du df
df.shape

# Période couverte
df['Date_Commande'].min()
df['Date_Commande'].max()

"""### 3- Quelques statistiques de bases"""

df.describe().T

"""Résumé des statistiques descriptives des variables numériques

Le jeu de données comprend 1 825 livraisons.

La variable cible Retard (en jours) présente une moyenne faible (0,44 jour) et une médiane nulle, ce qui indique que la majorité des livraisons sont effectuées à l’heure. Cependant, un retard maximal de 4 jours est observé, suggérant l’existence de quelques cas problématiques isolés.

Concernant les caractéristiques logistiques :

Le poids moyen des colis est d’environ 2,5 kg, avec une variabilité modérée.

Le prix moyen par livraison est de 1 228 €, avec une dispersion importante, traduisant une hétérogénéité des commandes.

Les dimensions des colis (largeur, longueur, hauteur) montrent une distribution équilibrée, sans valeurs extrêmes anormales.

Globalement, les données numériques sont cohérentes, sans anomalies évidentes, et montrent une variabilité suffisante pour analyser les facteurs influençant les retards de livraison.
"""

df.describe(include='object').T

"""Résumé des variables catégorielles

* Les variables catégorielles du jeu de données présentent une diversité maîtrisée, facilitant leur analyse.

* Les dates de commande et de livraison comptent respectivement 1 162 et 1 141 valeurs distinctes, ce qui confirme une bonne couverture temporelle des livraisons sur plusieurs années, sans concentration excessive sur quelques dates.

* Le délai prévu comporte 4 modalités, la plus fréquente étant “5 jours”, ce qui suggère une politique de livraison relativement standardisée.

* La région Île-de-France est la plus représentée, indiquant une forte concentration géographique de l’activité.

* Le canal Mobile App est le canal le plus utilisé, ce qui met en évidence l’importance du mobile dans le parcours client.

* Le type de produit “Accessoire” est le plus fréquent, traduisant un volume important de commandes sur cette catégorie.

* Enfin, ChronoPost est le transporteur le plus sollicité, ce qui en fait un acteur clé dans l’analyse des retards de livraison.

*Ces premiers résultats suggèrent que, bien que les retards soient globalement limités, leur analyse reste pertinente car ils peuvent impacter la satisfaction client et la performance opérationnelle.*

### 4- Détection des doublons
"""

df.duplicated().sum()

"""Il n'ya pas de doublons dans notee dataset"""



"""### 5- Détection des valeurs manquantes"""

df.isnull().sum()

"""analyse bivariée
fréquence
matrices de correlations
heatmap
histogramme

Il y'a pas de présence de valeurs manquantes.

### 6-Conversion des date

# Pour la période couverte, on convertis d’abord les dates, sinon min/max sur du texte peut être trompeur.
"""

df["Date_Commande"] = pd.to_datetime(df["Date_Commande"])
df["Date_Livraison"] = pd.to_datetime(df["Date_Livraison"])


print("Période couverte :")
print("Début :", df["Date_Commande"].min())
print("Fin   :", df["Date_Commande"].max())

"""La période couverte s’étend de 2019 à 2023, ce qui permet d’analyser l’évolution des retards dans le temps et d’identifier des tendances structurelles, notamment avant et après les perturbations logistiques récentes."""



"""## II- ANALYSE DE LA VARIABLE CIBLE : RETARD

## 1) Préparation pour l’EDA (variables utiles)
"""

# Variable cible
target = "Retard (en j)"

# Variable binaire : en retard / à l'heure (très utile pour les taux)
df["En_retard"] = df[target] > 0

# Variables temporelles
df["Annee"] = df["Date_Commande"].dt.year
df["Mois"] = df["Date_Commande"].dt.month
df["Trimestre"] = df["Date_Commande"].dt.quarter

# Volume (caractéristiques physiques)
df["Volume_cm3"] = df["Largeur (cm)"] * df["Longueur (cm)"] * df["Hauteur (cm)"]

"""On crée des variables dérivées (retard binaire, variables temporelles et volume) afin de faciliter les calculs de taux de retard, l’analyse saisonnière et l’étude de l’impact des caractéristiques physiques."""



"""# 2) Analyse de la variable cible : RETARD (univariée + fréquence + histogramme)

## 2.1 Statistiques + KPI globaux
"""

# Statistique la variable cible
df[target].describe()



"""Le retard moyen est faible (0,44 jour) et la médiane est nulle, ce qui signifie que la majorité des livraisons sont effectuées à l’heure.
Toutefois, la présence de retards allant jusqu’à 4 jours montre l’existence de situations problématiques ponctuelles, justifiant une analyse ciblée des facteurs explicatifs.
"""

# KPI glaubaux
taux_retard = df["En_retard"].mean() * 100
print(f"Taux de retard global : {taux_retard:.2f}%")
print(f"Retard moyen : {df[target].mean():.2f} jour(s)")
print(f"Retard médian : {df[target].median():.0f} jour")
print(f"Retard maximum : {df[target].max():.0f} jours")

"""Environ 17 % des livraisons présentent un retard, ce qui correspond à une livraison sur six.
Bien que la performance globale soit satisfaisante, ce taux reste suffisamment élevé pour impacter la satisfaction client et justifier un pilotage spécifique.
"""



"""## 2.2 Fréquences des retards"""

df[target].value_counts().sort_index()

"""La majorité des livraisons ont un retard nul, mais les livraisons en retard se répartissent sur plusieurs niveaux (1 à 4 jours).
Les retards ne sont donc pas uniquement marginaux et peuvent représenter des délais significatifs du point de vue client.

## 3.3 Distribution des retards positifs
"""

# Distribution de la variable cible (retards strictement positifs)
plt.figure(figsize=(8,5))
plt.hist(df.loc[df[target] > 0, target], bins=10)
plt.title("Distribution des retards (uniquement > 0 jour)")
plt.xlabel("Retard (jours)")
plt.ylabel("Nombre de livraisons en retard")
plt.show()



"""## 3-4) Distribution des retards"""

# Distribution des retards
plt.figure(figsize=(8,5))
plt.hist(df[target], bins=10)
plt.title("Distribution des retards (en jours)")
plt.xlabel("Retard (jours)")
plt.ylabel("Nombre de livraisons")
plt.show()

"""La distribution est fortement asymétrique, avec une concentration à 0 jour et une queue à droite.
Cela confirme que les retards concernent une minorité de livraisons, mais suivent un schéma structuré plutôt qu’aléatoire.
"""



"""## 5) Analyse bivariée (facteurs explicatifs) — sans répétition"""

def analyse_groupe(col):
    """
    Résumé simple par catégorie :
    - nombre de livraisons
    - taux de retard (%)
    - retard moyen
    - retard max
    """
    res = df.groupby(col).agg(
        nb=("Livraison_ID","count"),
        taux_retard=("En_retard","mean"),
        retard_moyen=(target,"mean"),
        retard_max=(target,"max")
    )
    res["taux_retard"] = (res["taux_retard"] * 100).round(2)
    res["retard_moyen"] = res["retard_moyen"].round(2)
    return res.sort_values("taux_retard", ascending=False)

res_transp = analyse_groupe("Transporteur")
res_transp[res_transp["nb"] >= 20]

"""Les transporteurs affichent des performances globalement proches, mais avec des écarts mesurables.
Aucun transporteur n’est systématiquement performant ou défaillant, ce qui invite à approfondir l’analyse par contexte régional.
"""



"""### 5.1 Analyse par Région"""

analyse_groupe("Région")

"""Les taux de retard varient sensiblement selon les régions.
Les régions les plus denses ou les plus sollicitées logistiquement présentent des taux de retard plus élevés, suggérant une influence du contexte territorial sur la performance de livraison.
"""

# Visualisation : taux de retard par région
tmp = analyse_groupe("Région").reset_index()

plt.figure(figsize=(10,5))
sns.barplot(data=tmp, x="Région", y="taux_retard")
plt.title("Taux de retard par région (%)")
plt.xticks(rotation=45, ha="right")
plt.show()

"""Certaines régions sont plus représentées que d’autres, notamment l’Île-de-France, ce qui reflète une concentration géographique de l’activité logistique."""



"""### 5.2 Analyse par Transporteur"""

analyse_groupe("Transporteur")

tmp = analyse_groupe("Transporteur").reset_index()

plt.figure(figsize=(10,5))
sns.barplot(data=tmp, x="Transporteur", y="taux_retard")
plt.title("Taux de retard par transporteur (%)")
plt.xticks(rotation=45, ha="right")
plt.show()

# Boxplot
plt.figure(figsize=(10,5))
sns.boxplot(data=df, x="Transporteur", y=target)
plt.title("Distribution du retard par transporteur (boxplot)")
plt.xticks(rotation=45, ha="right")
plt.show()



"""### 5.3 Analyse par Type_Produit"""

analyse_groupe("Type_Produit")

tmp = analyse_groupe("Type_Produit").reset_index()

plt.figure(figsize=(10,5))
sns.barplot(data=tmp, x="Type_Produit", y="taux_retard")
plt.title("Taux de retard par type de produit (%)")
plt.xticks(rotation=45, ha="right")
plt.show()

"""Les taux de retard diffèrent selon le type de produit.
Les produits technologiques comme les tablettes et smartphones présentent davantage de retards, ce qui peut être lié à des contraintes logistiques spécifiques (fragilité, contrôle, disponibilité).
"""



"""### 5.4 Analyse par Canal"""

analyse_groupe("Canal")

# Histogramme du taux de retard par canal
tmp = analyse_groupe("Canal").reset_index()

plt.figure(figsize=(8,5))
sns.barplot(data=tmp, x="Canal", y="taux_retard")
plt.title("Taux de retard par canal (%)")
plt.xticks(rotation=30, ha="right")
plt.show()

"""Les écarts de taux de retard entre les canaux sont faibles.
Le canal de commande ne semble donc pas être un facteur déterminant des retards, mais plutôt une variable de contexte.
"""



"""## 6) Caractéristiques physiques (poids/volume/prix) + bivariée

### 6.1 Corrélations simples avec la cible
"""

df[[target, "Poids (kg)", "Volume_cm3", "Prix (€)"]].corr()[target].sort_values(ascending=False)

"""Les caractéristiques physiques des colis présentent des distributions cohérentes, sans valeurs extrêmes anormales.
La variabilité observée est suffisante pour tester leur éventuel impact sur les retards de livraison.
"""





"""### 6.2 Scatter simple (poids vs retard)"""

plt.figure(figsize=(7,5))
plt.scatter(df["Poids (kg)"], df[target], alpha=0.4)
plt.title("Poids vs Retard")
plt.xlabel("Poids (kg)")
plt.ylabel("Retard (jours)")
plt.show()

"""Les retards sont observés pour tous les niveaux de poids, sans tendance claire.
Cette visualisation confirme l’absence de lien entre le poids du colis et le retard.
"""



"""## 7) Matrice de corrélation + Heatmap (numériques)"""

num_cols = ["Retard (en j)", "Poids (kg)", "Prix (€)", "Largeur (cm)", "Longueur (cm)", "Hauteur (cm)", "Volume_cm3"]
corr = df[num_cols].corr()

plt.figure(figsize=(10,6))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Heatmap des corrélations (variables numériques)")
plt.show()

"""La heatmap montre que seules les variables de dimensions sont fortement corrélées entre elles, ce qui est attendu.
Le retard reste indépendant des autres variables numériques, renforçant l’hypothèse d’un phénomène organisationnel plutôt que physique.
"""



"""## 8) Analyse temporelle (année / mois / trimestre)"""

temp = df.groupby("Annee").agg(
    nb=("Livraison_ID","count"),
    taux_retard=("En_retard","mean"),
    retard_moyen=(target,"mean")
)
temp["taux_retard"] = temp["taux_retard"] * 100
temp.round(2)

# Graphique : évolution du taux de retard par année
plt.figure(figsize=(8,5))
plt.plot(temp.index, temp["taux_retard"], marker="o")
plt.title("Évolution du taux de retard par année")
plt.xlabel("Année")
plt.ylabel("Taux de retard (%)")
plt.grid(True, alpha=0.3)
plt.show()

"""La heatmap montre que seules les variables de dimensions sont fortement corrélées entre elles, ce qui est attendu.
Le retard reste indépendant des autres variables numériques, renforçant l’hypothèse d’un phénomène organisationnel plutôt que physique.
"""



# Evolution mensuelle
mensuel = df.groupby(["Annee","Mois"]).agg(taux_retard=("En_retard","mean")).reset_index()
mensuel["taux_retard"] *= 100
mensuel["Periode"] = mensuel["Annee"].astype(str) + "-" + mensuel["Mois"].astype(str).str.zfill(2)

plt.figure(figsize=(12,5))
plt.plot(mensuel["Periode"], mensuel["taux_retard"])
plt.title("Évolution mensuelle du taux de retard")
plt.xlabel("Période (année-mois)")
plt.ylabel("Taux de retard (%)")
plt.xticks(rotation=90)
plt.grid(True, alpha=0.3)
plt.show()

"""## 9) Analyse par délai prévu

### 9.1) Région × Transporteur (top combinaisons)
"""

croise = df.groupby(["Région","Transporteur"]).agg(
    nb=("Livraison_ID","count"),
    taux_retard=("En_retard","mean"),
    retard_moyen=(target,"mean")
).reset_index()

croise["taux_retard"] = croise["taux_retard"] * 100

# Seuil pour éviter les biais sur très peu de livraisons
croise = croise[croise["nb"] >= 10].sort_values("taux_retard", ascending=False)

croise.head(10)

"""Certaines combinaisons Région × Transporteur présentent des taux de retard nettement supérieurs à la moyenne.
Cela indique que la performance logistique dépend fortement du contexte local et des conditions d’exploitation propres à chaque région.
"""



"""### 9.2) Heatmap croisée Région x Transporteur (taux de retard)"""

# Heatmap croisée Région x Transporteur (taux de retard)
pivot = df.pivot_table(index="Région", columns="Transporteur", values="En_retard", aggfunc="mean")
pivot = pivot * 100

plt.figure(figsize=(12,6))
sns.heatmap(pivot, annot=False, cmap="Reds")
plt.title("Heatmap du taux de retard (%) : Région x Transporteur")
plt.xlabel("Transporteur")
plt.ylabel("Région")
plt.show()

"""La heatmap met en évidence des zones critiques facilement identifiables visuellement.
Elle confirme que le pilotage de la performance doit être réalisé à un niveau local plutôt que global.
"""



"""## 10 Analyse par délai prévu"""

# Analyse par délai prévu
analyse_groupe("Délais_Prévu")

# Visualisation : taux de retard par délai prévu
tmp = analyse_groupe("Délais_Prévu").reset_index()

plt.figure(figsize=(7,4))
sns.barplot(data=tmp, x="Délais_Prévu", y="taux_retard")
plt.title("Taux de retard par délai prévu (%)")
plt.xlabel("Délai prévu")
plt.ylabel("Taux de retard (%)")
plt.show()

"""Les délais prévus les plus courts sont associés à des taux de retard plus élevés.
Cela montre que des promesses de livraison trop ambitieuses laissent moins de marge pour absorber les aléas logistiques.
"""



"""## 11) Synthèse finale (texte + chiffres)"""

print("SYNTHÈSE")
print(f"- Taux de retard global : {taux_retard:.2f}%")
print(f"- Retard moyen : {df[target].mean():.2f} jour(s)")
print(f"- Retard max : {df[target].max()} jours")

print("\nTop 3 transporteurs (taux retard) :")
print(analyse_groupe("Transporteur").head(3)[["taux_retard","retard_moyen","nb"]])

print("\nTop 3 régions (taux retard) :")
print(analyse_groupe("Région").head(3)[["taux_retard","retard_moyen","nb"]])

"""Les régions et transporteurs les plus contributeurs aux retards sont clairement identifiés.
Ces éléments constituent des priorités d’action pour améliorer la performance globale.
"""





"""# III - APPROFONDISSEMENT : MODÉLISATION DU RISQUE DE RETARD (RÉGRESSION LOGISTIQUE)

Objectif :
À partir des résultats de l’EDA, on cherche à expliquer/predire la probabilité qu’une livraison soit en retard (Retard > 0). C’est plus pertinent qu’une régression linéaire car la variable "Retard (en j)" est très concentrée sur 0.
"""

# 1) Création de la cible binaire (si ce n'est pas déjà fait)
df["en_retard"] = (df[target] > 0).astype(int)

# 2) Sélection des variables explicatives (facteurs identifiés par l’EDA)
# on privilégie les variables contextuelles (région, transporteur, type, délai, temps)
features = ["Région", "Transporteur", "Type_Produit", "Canal", "Délais_Prévu", "Annee", "Mois"]

X = df[features].copy()
y = df["en_retard"].copy()

# 3) Split train/test (on garde une partie des données pour évaluer le modèle)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 4) Pipeline : encodage des variables catégorielles + modèle logistique
# - OneHotEncoder transforme les catégories en variables numériques
# - LogisticRegression apprend les coefficients explicatifs
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

cat_cols = ["Région", "Transporteur", "Type_Produit", "Canal", "Délais_Prévu"]
num_cols = ["Annee", "Mois"]

preprocess = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
        ("num", "passthrough", num_cols)
    ]
)

model = LogisticRegression(max_iter=1000, class_weight="balanced")  # balanced utile si classe "retard" minoritaire

pipe = Pipeline(steps=[
    ("preprocess", preprocess),
    ("model", model)
])

# 5) Entraînement
pipe.fit(X_train, y_train)

# 6) Évaluation : classification report + matrice de confusion + AUC
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, RocCurveDisplay

y_pred = pipe.predict(X_test)
y_proba = pipe.predict_proba(X_test)[:, 1]

print("\n--- Rapport de classification (test) ---")
print(classification_report(y_test, y_pred))

print("\n--- Matrice de confusion (test) ---")
print(confusion_matrix(y_test, y_pred))

auc = roc_auc_score(y_test, y_proba)
print(f"\nAUC (test) : {auc:.3f}")

# Courbe ROC (visuel rapide)
RocCurveDisplay.from_predictions(y_test, y_proba)
plt.title("Courbe ROC - Régression logistique")
plt.show()

"""L'AUC mesure la capacité du modèle à distinguer retards vs non-retards.
La matrice de confusion montre les erreurs : faux positifs/faux négatifs.
On ne cherche pas ici une performance parfaite, mais à confirmer les facteurs explicatifs.
"""

# 7) Interprétation : coefficients / importance (odds ratios)
# Objectif : comprendre quels facteurs augmentent ou réduisent le risque de retard.

# Récupération des noms de variables après encodage
ohe = pipe.named_steps["preprocess"].named_transformers_["cat"]
cat_feature_names = ohe.get_feature_names_out(cat_cols)
feature_names = list(cat_feature_names) + num_cols

# Coefficients du modèle
coefs = pipe.named_steps["model"].coef_[0]

coef_df = pd.DataFrame({
    "Variable": feature_names,
    "Coefficient": coefs
})

# Odds Ratio = exp(coefficient) : plus parlant en métier
coef_df["Odds_Ratio"] = np.exp(coef_df["Coefficient"])

# On affiche les variables qui augmentent le plus / diminuent le plus le risque
coef_df_sorted = coef_df.sort_values("Odds_Ratio", ascending=False)

print("\n--- Top facteurs qui AUGMENTENT le risque de retard ---")
print(coef_df_sorted.head(10))

print("\n--- Top facteurs qui RÉDUISENT le risque de retard ---")
print(coef_df_sorted.tail(10).sort_values("Odds_Ratio"))

"""* Odds_Ratio > 1 : augmente la probabilité de retard
* Odds_Ratio < 1 : diminue la probabilité de retard
* Cette partie valide et quantifie les enseignements de l’EDA

(ex : certaines régions/transporteurs/types de produit sont plus “à risque”).
"""

# 8) Bonus Dashboard : score de risque par livraison (probabilité de retard)
df["proba_retard"] = pipe.predict_proba(X)[:, 1]

print("\nAperçu des probabilités de retard :")
df[["Livraison_ID", "Région", "Transporteur", "Type_Produit", "Délais_Prévu", "Annee", "Mois", "proba_retard"]].head()

# Exemple : top 10 livraisons les plus à risque (utile pour un tableau dans Power BI)
df.sort_values("proba_retard", ascending=False).head(10)

"""Cette modélisation confirme les résultats de l’analyse exploratoire : les retards de livraison sont principalement liés à des facteurs contextuels (région, transporteur, type de produit, délai prévu) plutôt qu’aux caractéristiques physiques des colis.
Le modèle permet d’estimer un score de risque par livraison, ouvrant la voie à un pilotage proactif de la performance logistique via le tableau de bord décisionnel.
"""

# 9) Export dataset enrichi (avec proba_retard) pour Power BI
output_path = "/content/drive/MyDrive/Management de projet data/boxintime_enrichi_avec_risque.csv"
df.to_csv(output_path, index=False)
print("\nExport réalisé :", output_path)





"""# IV- SYNTHÈSE GLOBALE – ANALYSE EXPLORATOIRE DES RETARDS BOXTIME

## 1)Situation générale : une performance globalement correcte mais sous tension

L’analyse exploratoire montre que la performance de livraison de Boxtime est globalement satisfaisante, avec :

* 83 % des livraisons effectuées à l’heure

* 17,1 % de livraisons en retard

* Un retard moyen inférieur à 1 jour

Ces résultats indiquent que les retards ne constituent pas un dysfonctionnement massif du système logistique.


Cependant, leur fréquence non négligeable et leur augmentation dans le temps en font un enjeu stratégique, notamment en termes de satisfaction client et de crédibilité des promesses de livraison.

_

*Le problème n’est pas généralisé, mais il est structurel et croissant.*
"""



"""## 2)Nature des retards : un phénomène non aléatoire

Les analyses univariées et bivariées montrent que les retards :

* ne sont pas expliqués par les caractéristiques physiques des colis (poids, volume, prix),

* mais dépendent fortement du contexte logistique et organisationnel.


_

Les retards apparaissent de manière structurée, concentrés :

* sur certaines zones géographiques,

* chez certains transporteurs,

* et surtout sur des combinaisons spécifiques Région × Transporteur.

_

*Les retards sont le résultat d’un système, pas d’un hasard.*

#
"""



"""## 3) Facteurs explicatifs prioritaires
🔹 Facteurs majeurs identifiés

* Région : les zones à forte densité logistique (Île-de-France, AURA, PACA) concentrent davantage de retards.

* Transporteur : les performances varient, sans qu’aucun acteur ne soit systématiquement défaillant.

* Couple Région × Transporteur : c’est le niveau d’analyse le plus discriminant.

* Temps : une hausse continue du taux de retard entre 2019 et 2023.

_


🔹 Facteurs secondaires ou non explicatifs

* Canal de commande

* Poids, volume, prix des colis

--

*Le pilotage doit être local, ciblé et contextuel.*
"""



"""
L’analyse par délai prévu révèle un point contre-intuitif mais essentiel :

Les délais les plus courts sont associés à des taux de retard plus élevés.

Allonger légèrement les délais permet de réduire la pression opérationnelle."""



"""## 4- Implications directes pour le dashboard décisionnel

Cette analyse permet de définir clairement le rôle du dashboard :

Objectif du dashboard

* Piloter les retards de livraison là où ils se produisent réellement, et non au niveau global.
"""



"""## 5) Ce que le dashboard DOIT mettre en avant

 Indicateurs prioritaires (à afficher en premier)

* Taux de retard global

* Évolution du taux de retard dans le temps

* Taux de retard par région

* Taux de retard par transporteur

* Heatmap Région × Transporteur (visuel central)


-


 Axes d’analyse indispensables

* Comparaison régionale

* Comparaison entre transporteurs

* Identification rapide des zones à risque

* Suivi temporel de la dégradation ou amélioration
"""



"""# Conclusion
L’analyse exploratoire des retards de livraison chez Boxtime met en évidence un phénomène modéré mais structurel, en augmentation dans le temps et fortement dépendant du contexte logistique.


Les résultats montrent que les leviers d’amélioration se situent principalement au niveau local, à travers le pilotage des performances par région et par transporteur, ainsi que l’ajustement des délais annoncés.


Ces enseignements orientent la conception d’un tableau de bord décisionnel centré sur l’identification rapide des zones à risque et la priorisation des actions correctives.
"""